### PR TITLE
Migrate to dotnet tooling 1.0

### PR DESCRIPTION
**Pull request by mrahhal**
Original PR at #34

@Abdruggi I had to get this out asap since some of the internal projects I work on are already migrated. I used your commit as a reference since you've done a lot of the work (the first commit is still attributed to you so thanks a lot).

That being said, there are still things to be done. This branch as it is right now works, but we're calling an external process manually when running some operations, and this is showing a temp console window (yikes). I'd like to improve on some of the other points too (like the `ProjectReader`).

### CODE REVIEW

**Comment by Abdruggi** [comment]
I wrote the change set out of the same reason. Just write me if I can help refactoring/improve the project. I was hoping Microsoft will bring an official package. But it doesn’t look like.

**Comment by AlonCG** [comment]
Thanks all!

**Comment by mrahhal** [comment]
@Abdruggi I definitely will. You can review the first commit which I really took from your work, kept it the same just cleaned a bit.

The only major thing I want to change before I release `1.1.0` is [this](https://github.com/mrahhal/Migrator.EF6/pull/35/files#diff-63bc3615f80fc61cfc54cbf67b71c5aeR45). I'm already looking into whether dispatching will do what we want.

> I was hoping Microsoft will bring an official package.

Actually, the only reason I didn't attempt to do the migration the moment VS RC got out is because I genuinely thought there would be something that works at RTM (because it's the first stable tooling version and all). But appears nothing is planned at all.

**Comment by mrahhal** [comment]
OK so that was easy, right now everything works as expected. But I'm still not a lot happy with `ProjectReader`, seems like a roundabout way to get common info about the target project. There must be something that we can use (or maybe there isn't? Which sounds extremely odd).

**Comment by Abdruggi** [comment]
Parsing of csproj files is not that easy because of conditions. The environment you compile against determines the final values. I will do some research this evening.

**Comment by mrahhal** [comment]
I was hoping the sdk itself will give us a public api for that. I mean, obviously the `dotnet` command parses the project so I was wondering why that functionality isn't exposed.

But this is good enough for now. I'll make a final review before releasing.

**Comment by Abdruggi** [comment]
Yes that would be desirable. Or maybe some Roslyn API‘s to get the information.

**Pull request merged**
